apiVersion: v1
kind:  Service
metadata:
  labels:
    app: conversao
  name: svc-conversao
  namespace: devops
spec:
  selector:
    app: conversao
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  type: NodePort 
